name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run smoke test
      run: uv run python test_smoke.py

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run unit tests with pytest
      run: uv run python -m pytest tests/ -v
