name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run smoke test
      run: uv run python test_smoke.py

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run unit tests with pytest
      run: uv run python -m pytest tests/ -v

  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run integration test (limited data)
      run: |
        export BGGFINNA_TEST=1
        uv run python run_pipeline.py
      
    - name: Verify integration test outputs
      run: |
        ls -la data/test/
        test -f data/test/finna_board_games.csv
        test -f data/test/finna_bgg_relations.csv
        test -f data/test/bgg_games.csv
        test -f data/test/boardgames.db
        echo "All expected files created successfully"